name: Coverage

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get -y install ninja-build

      - name: Install Conan
        run: pip install conan

      - name: Conan version
        run: conan --version

      - name: Setup Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.conan2/p/
          key: ${{ runner.os }}-conan-${{ hashFiles('**/conan.lock') }}

      - name: Setup default profile
        run: conan profile detect

      - name: Install profiles
        run: conan config install https://github.com/ooonak/conanconf.git -t git --args="-b main" -sf=profiles -tf=profiles

      - name: Build
        run: conan build . -pr x86_64-clang-18-coverage --build=missing

      - name: Run Tests with Coverage
        run: |
          LLVM_PROFILE_FILE="coverage.profraw" ./build/Debug/tests/clrppTests
          llvm-profdata merge -sparse coverage.profraw -o coverage.profdata
          llvm-cov report ./build/Debug/tests/clrppTests -instr-profile=coverage.profdata -use-color > coverage.txt

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.txt

      - name: Extract Coverage Percentage
        run: |
          COVERAGE=$(grep -o 'TOTAL.*[0-9]\{1,3\}\.[0-9]\{2\}%' coverage.txt | awk '{print $NF}' | tr -d '%')
          echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV
          echo "$COVERAGE" > coverage_badge.json

      - name: Generate Coverage Badge
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"schemaVersion":1, "label":"coverage", "message":"'${{ env.COVERAGE }}'%", "color":"green"}' \
          https://img.shields.io/endpoint > coverage_badge.json

      - name: Upload Badge
        uses: actions/upload-artifact@v4
        with:
          name: coverage-badge
          path: coverage_badge.json

      - name: Commit and Push Badge  # Fixed indentation here
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout gh-pages || git checkout --orphan gh-pages
          mv coverage_badge.json coverage.json
          git add coverage.json
          git commit -m "Update coverage badge"
          git push origin gh-pages
